name: Build and Test
on:
  push:
    branches:
      - main
    tags-ignore: [ v.* ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --depth=100 origin +refs/tags/*:refs/tags/*

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6

      - name: Set up JDK 11
        uses: coursier/setup-action@v1
        with:
            jvm:
              adopt:11

      - name: sbt test
        run: sbt --client ^test

      - name: sbt scripted
        run: sbt --client '^scripted bom/*'
